---
ignore:
- chatter
- deferred
reopen:
- "*"
- "-question"
no_debug_id: |
  It looks like you did not upload an error report. The error report is important; it gives @retorquere your current BBT settings and a copy of the problematic reference as a test case so he can best replicate your problem. Without it, @retorquere is effectively blind.

  If your issue relates to how BBT behaves around a specific reference(s), select at least one of the problematic reference(s), right-click it, and submit an BBT error report from that popup menu.

  If the issue does not relate to references and is of a more general nature, generate an error report by restarting Zotero with debugging enabled (Help -> Debug Output Logging -> Restart with logging enabled), reproducing your problem, and selecting "Report Better BibTeX error" from the help menu.

  Once done, you will see a debug ID in red. Please post that debug id in the issue here.

  Thank you!
