dist: xenial
language: python
python:
  - 3.7
services:
  - xvfb

# https://github.com/travis-ci/travis-ci/issues/8920
# https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-348435959
before_install:
  - python3 -c 'import os,sys; os.set_blocking(sys.stdout.fileno(), True)'
  - python3 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); print("blocking:", flags&os.O_NONBLOCK == 0);'
  - curl -sL https://github.com/retorquere/zotero-deb/releases/download/apt-get/install.sh | sudo bash
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install zotero jurism default-jre libreoffice-java-common

cache:
  npm: true
  bundler: true
  pip: true
  apt: true
  directories:
  - node_modules
  - .cache/pip

script:
  - ./util/build-assets fetch || travis_terminate 1
  - ./test/behave --no-capture -f travis --tags $TAGS

after_failure:
  - ./util/build-assets pop
  - export fileio=$(curl -F "file=@$HOME/.BBTZ5TEST.log" https://file.io) && echo $fileio

stages:
  - build
  - test
  - release
  - cleanup

jobs:
  include:
  - stage: build
    before_install:
      - travis_retry sudo snap install hugo --channel=extended
    script:
      - npm run build
      - travis_retry ./util/build-assets stash

  - stage: test
    env:
    - ZOTERO=zotero
    - TAGS="@test-cluster-1"

  - stage: test
    env:
    - ZOTERO=zotero
    - TAGS="~@test-cluster-1"

  - stage: test
    env:
    - ZOTERO=jurism
    - TAGS="@test-cluster-1"

  - stage: test
    env:
    - ZOTERO=jurism
    - TAGS="~@test-cluster-1"

  - stage: release
    if: env(TRAVIS_EVENT_TYPE) != cron AND env(TRAVIS_EVENT_TYPE) != pull_request
    before_install: true
    script:
      - ./util/build-assets fetch || travis_terminate 1
      - npm run release
      - ./util/build-assets pop

  - stage: cleanup
    if: env(TRAVIS_EVENT_TYPE) = cron OR env(TRAVIS_EVENT_TYPE) = pull_request
    before_install: true
    script:
      - ./util/build-assets pop
