language: python
python:
  - 3.6

cache:
  yarn: true
  bundler: true
  pip: true
  directories:
  - node_modules
  - vendor/bundle
  - downloads
  - .cache/pip
  - xpi

script: |
  if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]] || [[ ! -z "$TRAVIS_TAG" ]] || [[ "$TRAVIS_COMMIT_MESSAGE" == *"#nightly"* ]]; then
    export NIGHTLY=""
    export TRACE=true
  else
    export NIGHTLY="and not @nightly"
  fi

  xvfb-run bundle exec cucumber --format pretty --strict --tags "$CLUSTER $NIGHTLY"

jobs:
  include:
  - stage: build
    script: |-
      gem install bundler
      gem update bundler
      bundle config
      bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

      mkdir -p bin downloads/zotero downloads/juris-m
      ./zotero5_installer.py --client $ZOTERO --version latest --location $TRAVIS_BUILD_DIR/bin --datadir home --replace --cache downloads/$CLIENT

      if [[ "$TRAVIS_COMMIT_MESSAGE" == *"#trace"* ]]; then
        export TRACE=true
      fi
      yarn run build

  - stage: test
    install: true
    env:
    - ZOTERO=zotero
    - CLUSTER="@test-cluster-1"
    after_failure: curl --upload-file ~/.BBTZ5TEST.log https://transfer.sh/BBTZ5TEST-$TRAVIS_BUILD_NUMBER.txt

  - stage: test
    install: true
    env:
    - ZOTERO=zotero
    - CLUSTER="not @test-cluster-1"
    after_failure: curl --upload-file ~/.BBTZ5TEST.log https://transfer.sh/BBTZ5TEST-$TRAVIS_BUILD_NUMBER.txt

  - stage: test
    install: true
    env:
    - ZOTERO=jurism
    - CLUSTER="@test-cluster-1"
    after_failure: curl --upload-file ~/.BBTZ5TEST.log https://transfer.sh/BBTZ5TEST-$TRAVIS_BUILD_NUMBER.txt

  - stage: test
    install: true
    env:
    - ZOTERO=jurism
    - CLUSTER="not @test-cluster-1"
    after_failure: curl --upload-file ~/.BBTZ5TEST.log https://transfer.sh/BBTZ5TEST-$TRAVIS_BUILD_NUMBER.txt

  - stage: release
    script: |-
      if [[ "$TRAVIS_EVENT_TYPE" != "cron" ]]; then
        ls -l xpi
        yarn run release
        rm -rf xpi
      fi
