env:
  - ZOTERO=zotero CLUSTER="@test-cluster-1" RELEASE=true
  - ZOTERO=zotero CLUSTER="not @test-cluster-1"
  - ZOTERO=jurism CLUSTER="@test-cluster-1"
  - ZOTERO=jurism CLUSTER="not @test-cluster-1"

# is caching parallel-safe?
cache:
  yarn: true
  bundler: true
  directories:
    - node_modules
    - vendor/bundle
    - download

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

jobs:
  include:
    - stage: test
      script: |-
        export DISPLAY=:1.0
        git log --format=%B -n 1 $CIRCLE_SHA1 | grep '#trace' &> /dev/null
        if [ $? == 0 ]; then
          export TRACE=true
        fi

        git submodule sync && git submodule update --init --recursive

        yarn install

        gem install bundler
        gem update bundler
        bundle config
        bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

        mkdir -p bin downloads/zotero downloads/juris-m
        ./zotero5_installer.py --client $ZOTERO --version latest --location $TRAVIS_BUILD_DIR/bin --datadir profile --replace --cache downloads/zotero

        yarn run build

        if [ "$TRAVIS_EVENT_TYPE" = "cron" -o "$TRAVIS_TAG" ]; then
          export NIGHTLY=""
          export TRACE=true
        else
          export NIGHTLY="not @nightly and"
        fi

        bundle exec cucumber --format pretty --strict --tags "$CLUSTER $NIGHTLY"

    - stage: release
      script: |-
        [[ "$RELEASE" = "true" ]] && yarn run release
