cache:
  yarn: true
  bundler: true
  directories:
    - node_modules
    - vendor/bundle
    - download

_script: &script
  script: |-
    set -e
    set -x

    if [[ $TRAVIS_COMMIT_MESSAGE = *"#trace"* ]]; then
      export TRACE=true
    fi

    #git submodule sync && git submodule update --init --recursive

    yarn install

    gem install bundler
    gem update bundler
    bundle config
    bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

    mkdir -p bin downloads/zotero downloads/juris-m
    ./zotero5_installer.py --client $ZOTERO --version latest --location $TRAVIS_BUILD_DIR/bin --datadir home --replace --cache downloads/$CLIENT

    if [ "$TRAVIS_EVENT_TYPE" = "cron" -o "$TRAVIS_TAG" ]; then
      export NIGHTLY=""
      export TRACE=true
    else
      export NIGHTLY="not @nightly and"
    fi

    xvfb-run bundle exec cucumber --format pretty --strict --tags "$CLUSTER $NIGHTLY"

  after_failure:
    - tail --lines=2000 ~/.BBTZ5TEST.log

jobs:
  include:
    - stage: test
      env:
      - ZOTERO=zotero
      - CLUSTER="@test-cluster-1"
      <<: *script

    - stage: test
      env:
      - ZOTERO=zotero
      - CLUSTER="not @test-cluster-1"
      <<: *script

    - stage: test
      env:
      - ZOTERO=jurism
      - CLUSTER="@test-cluster-1"
      <<: *script

    - stage: test
      env:
      - ZOTERO=jurism
      - CLUSTER="not @test-cluster-1"
      <<: *script

    - stage: release
      script: |-
        yarn install
        yarn run release
