dist: xenial
language: python
python:
  - 3.7
services:
  - xvfb

branches:
  except:
    - gh-pages

cache:
  npm: true
  bundler: true
  pip: true
  apt: true
  directories:
  - node_modules
  - .cache/pip

# the python stuff is for
# https://github.com/travis-ci/travis-ci/issues/8920
# https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-348435959
before_install:
  - python3 -c 'import os,sys; os.set_blocking(sys.stdout.fileno(), True)'
  - python3 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); print("blocking:", flags&os.O_NONBLOCK == 0);'
  - curl -sL https://github.com/retorquere/zotero-deb/releases/download/apt-get/install.sh | sudo bash
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install $CLIENT
  - travis_retry sudo ./util/install-beta $CLIENT
script:
  - ./util/build-assets fetch || travis_terminate 1
  - [[ $CLIENT = 'zotero' ] && ./test/behave

after_failure:
  - ./util/build-assets pop
  - export transfersh=$(curl --upload-file "$HOME/.BBTZ5TEST.log" https://transfer.sh/BBTZ5TEST.txt) && echo $transfersh

stages:
  - build
  - test
  - release
  - cleanup

jobs:
  include:
  - stage: build
    before_install: true
    script:
      - npm run build
      - travis_retry ./util/build-assets stash

  - stage: test
    env:
    - CLIENT=zotero
    - JOB=1
  - stage: test
    env:
    - CLIENT=zotero
    - JOB=2
  - stage: test
    env:
    - CLIENT=jurism
    - JOB=1
  - stage: test
    env:
    - CLIENT=jurism
    - JOB=2

  - stage: release
    if: env(TRAVIS_EVENT_TYPE) != cron AND env(TRAVIS_EVENT_TYPE) != pull_request
    before_install: true
    script:
      - ./util/build-assets fetch || travis_terminate 1
      - npm run release
    before_deploy:
      - travis_retry sudo snap install hugo --channel=extended
      - npm run docs:deploy
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      local_dir: site/public
      keep_history: true
      on:
        branch: master
    after_script:
      - ./util/build-assets pop

  - stage: cleanup
    if: env(TRAVIS_EVENT_TYPE) = cron OR env(TRAVIS_EVENT_TYPE) = pull_request
    before_install: true
    script:
      - ./util/build-assets pop
