plugins:
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter

repository: retorquere/zotero-better-bibtex

permalink: pretty

optional_front_matter:
  remove_originals: true

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false
