name: Better BibTeX

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: install python/node dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        npm install
    - run: npm run build
    - name: build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          xpi
          gen

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        client: [ 'zotero', 'jurism' ]
        slice: [ '1', '2' ]
    steps:
    - uses: actions/checkout@v2
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts
    - name: install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - run: curl -sL https://github.com/retorquere/zotero-deb/releases/download/apt-get/install.sh | sudo bash
    - run: sudo apt-get update
    - run: sudo apt-get install ${{ matrix.client }}
    - run: sudo ./util/install-beta ${{ matrix.client }}
    - run: ./test/behave --format json.pretty --outfile behave.json --format travis --balance ${{ matrix.slice }}

