name: 'Manage issues and nag about support logs'

on:
  issues:
    types: [opened, edited, closed]
  issue_comment:
    types: [created, edited, closed]

jobs:
  nag:
    runs-on: ubuntu-latest
    steps:
      - uses: retorquere/label-gun@master
        with:
          token: ${{ github.token }}
